spring:
  application:
    name: spring-completo
  datasource:
    url: jdbc:h2:mem:shop
    username: sa
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console